version: "3.9"
services:
  db:
    image: postgres:15
    container_name: ls_db
    restart: always
    environment:
      POSTGRES_USER: ls_backend_user
      POSTGRES_PASSWORD: ls_backend_pass
      POSTGRES_DB: ls_backend_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
